In [1]:
import numpy as np

In [3]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
array = np.full(10, 7)
array

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [6]:
array = np.repeat(8, 10)
array

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [8]:
array = np.repeat([1, 2, 3], 5)
array

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [9]:
array = np.repeat([5, 6, 7], [1, 2, 3])
array

array([5, 6, 6, 7, 7, 7])

In [11]:
element = array[0]
element

5

In [12]:
element = array[2]
element

6

In [13]:
print(array[[1, 2, 3]])

[6 6 7]


In [15]:
array

array([5, 6, 6, 7, 7, 7])

In [16]:
array[1] = 1
array

array([5, 1, 6, 7, 7, 7])

In [18]:
elements = [1, 2, 3, 4, 5]
array = np.array(elements)
print(elements)
print(array)
print(type(elements))
print(type(array))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>


In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
thresholds = np.linspace(0, 1, 11)
thresholds

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [25]:
zeros = np.zeros(10, dtype=np.uint8)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

**Warning:** Be careful when choosing the dtype for an array. If you accidentally choose a dtype that’s too narrow, NumPy won’t warn you when you put in a big number. It will simply truncate them.

In [26]:
zeros[0] = 300
print(zeros[0])

44


/var/folders/96/_scwp5r13h12qhlr0r4c0xx80000gn/T/ipykernel_43085/2020449431.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  zeros[0] = 300


In [28]:
for i in np.arange(5):
    print(i)

0
1
2
3
4


In [29]:
zeros = np.zeros((5, 2), dtype=np.float32)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [31]:
print(zeros.shape)

(5, 2)


In [32]:
numbers = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

numbers = np.array(numbers)
print(numbers)
print(type(numbers))
print(numbers.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


In [33]:
print(numbers[1,2])

6


In [34]:
numbers[0, 1] = 10
numbers

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
numbers[0]

array([ 1, 10,  3])

In [37]:
numbers[:, 2]

array([3, 6, 9])

In [39]:
numbers[1] = [1, 1, 1]
numbers

array([[ 1, 10,  3],
       [ 1,  1,  1],
       [ 7,  8,  9]])

In [41]:
numbers[:, 2] = [1, 1, 1]
numbers

array([[ 1, 10,  1],
       [ 1,  1,  1],
       [ 7,  8,  1]])

In [43]:
arr = np.random.rand(5, 2)
arr

array([[0.69460724, 0.41150396],
       [0.30736589, 0.94214773],
       [0.17192654, 0.5893782 ],
       [0.24059219, 0.96575353],
       [0.52729718, 0.79187616]])

In [53]:
np.random.seed(2)
arr = np.random.rand(5, 2)
arr

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [73]:
np.random.seed(2)
arr = np.random.randn(5, 2)
arr

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [79]:
np.random.seed(2)
randint = np.random.randint(low=0, high=100, size=(5,2))
randint

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [81]:
idx = np.arange(5)
print('before shuffle', idx)

np.random.shuffle(idx)
print('after shuffle', idx)

before shuffle [0 1 2 3 4]
after shuffle [3 2 1 0 4]


In [82]:
rng =  np.arange(5)
rng

array([0, 1, 2, 3, 4])

In [83]:
rng * 2

array([0, 2, 4, 6, 8])

In [84]:
rng

array([0, 1, 2, 3, 4])

In [85]:
(rng - 1) * 3 / 2 + 1

array([-0.5,  1. ,  2.5,  4. ,  5.5])

In [90]:
np.random.seed(2)
noise = 0.01 * np.random.rand(5)
numbers = np.arange(5)
print(noise)
print(numbers)

[0.00435995 0.00025926 0.00549662 0.00435322 0.00420368]
[0 1 2 3 4]


In [92]:
result = numbers + noise
result

array([0.00435995, 1.00025926, 2.00549662, 3.00435322, 4.00420368])

In [93]:
result.round(4)

array([0.0044, 1.0003, 2.0055, 3.0044, 4.0042])

In [95]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [98]:
square = pred * pred
square

array([0.1936, 0.0009, 0.3025])

In [99]:
square = pred ** 2
square

array([0.1936, 0.0009, 0.3025])

In [101]:
pred_exp = np.exp(pred) # exponent
pred_log = np.log(pred) # logarithm
pred_sqrt = np.sqrt(pred) # square root

print(pred_exp)
print(pred_log)
print(pred_sqrt)

[1.55270722 1.03045453 1.73325302]
[-0.82098055 -3.5065579  -0.597837  ]
[0.66332496 0.17320508 0.74161985]


In [102]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [105]:
result = pred >= 0.5
result

array([False, False,  True])

In [106]:
np.random.seed(2)
pred1 = np.random.rand(3).round(2)
pred2 = np.random.rand(3).round(2)
print(pred1)
print(pred2)

[0.44 0.03 0.55]
[0.44 0.42 0.33]


In [107]:
pred1 >= pred2

array([ True, False,  True])

In [108]:
np.random.seed(2)
pred1 = np.random.rand(5) >= 0.3
pred2 = np.random.rand(5) >= 0.4
print(pred1)
print(pred2)

[ True False  True  True  True]
[False False  True False False]


In [110]:
res_and = pred1 & pred2
res_and

array([False, False,  True, False, False])

In [111]:
res_or = pred1 | pred2
res_or

array([ True, False,  True,  True,  True])

In [113]:
np.random.seed(2)
pred = np.random.rand(3).round(2)
pred

array([0.44, 0.03, 0.55])

In [115]:
pred_sum = pred.sum()
pred_sum

1.02

In [116]:
print('min = %.2f' % pred.min())
print('mean = %.2f' % pred.mean())
print('max = %.2f' % pred.max())
print('std = %.2f' % pred.std())

min = 0.03
mean = 0.34
max = 0.55
std = 0.22


In [117]:
np.random.seed(2)
matrix = np.random.rand(4, 3).round(2)
matrix

array([[0.44, 0.03, 0.55],
       [0.44, 0.42, 0.33],
       [0.2 , 0.62, 0.3 ],
       [0.27, 0.62, 0.53]])

In [118]:
matrix.max()

0.62

In [119]:
matrix.max(axis=1)

array([0.55, 0.44, 0.62, 0.62])

In [120]:
matrix.max(axis=0)

array([0.44, 0.62, 0.55])

In [121]:
matrix.sum(axis=1)

array([1.02, 1.19, 1.12, 1.42])

In [127]:
np.random.seed(2)
pred = np.random.rand(4).round(2)
pred

array([0.44, 0.03, 0.55, 0.44])

In [128]:
np.sort(pred)

array([0.03, 0.44, 0.44, 0.55])

In [125]:
pred.sort()
pred

array([0.03, 0.44, 0.44, 0.55])

In [129]:
idx = pred.argsort()
idx

array([1, 0, 3, 2])

In [130]:
pred[idx]

array([0.03, 0.44, 0.44, 0.55])

In [143]:
rng = np.arange(12)
rng.shape

(12,)

In [144]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [145]:
rng.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [146]:
rng.reshape(4, 4)

ValueError: cannot reshape array of size 12 into shape (4,4)

In [147]:
vec = np.arange(3)
mat = np.arange(6).reshape(3, 2)
print(vec)
print(mat)

[0 1 2]
[[0 1]
 [2 3]
 [4 5]]


In [148]:
np.concatenate([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [149]:
np.hstack([vec, vec])

array([0, 1, 2, 0, 1, 2])

In [150]:
np.hstack([mat, mat])

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5]])

In [151]:
np.concatenate([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [153]:
np.column_stack([mat, vec])

array([[0, 1, 0],
       [2, 3, 1],
       [4, 5, 2]])

In [154]:
np.column_stack([vec, vec])

array([[0, 0],
       [1, 1],
       [2, 2]])

In [155]:
np.vstack([vec, vec])

array([[0, 1, 2],
       [0, 1, 2]])

In [156]:
np.vstack([mat, mat])

array([[0, 1],
       [2, 3],
       [4, 5],
       [0, 1],
       [2, 3],
       [4, 5]])

In [157]:
np.vstack([vec, mat.T])

array([[0, 1, 2],
       [0, 2, 4],
       [1, 3, 5]])

In [159]:
np.random.seed(2)
mat = np.arange(15).reshape(5, 3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [160]:
mat[:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [161]:
mat[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [162]:
mat[:, :2]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13]])

In [163]:
mat[1:3, :2]

array([[3, 4],
       [6, 7]])

In [164]:
mat[[3, 0, 1]]

array([[ 9, 10, 11],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [165]:
mat[:, 0] % 2 == 1

array([False,  True, False,  True, False])

In [166]:
mat[mat[:, 0] % 2 == 1]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [174]:
a = np.array([1, 2, 3, 4, 5])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [175]:
f = np.array([1.1, 2.1, 3.1, 4.1, 5.1])
f.dtype

dtype('float64')

In [176]:
print(a.ndim)

1


In [177]:
a.shape

(5,)

In [178]:
a.size

5

In [179]:
a + f

array([ 2.1,  4.1,  6.1,  8.1, 10.1])

In [180]:
a * f

array([ 1.1,  4.2,  9.3, 16.4, 25.5])

In [181]:
a / f

array([0.90909091, 0.95238095, 0.96774194, 0.97560976, 0.98039216])

In [182]:
f ** a

array([1.10000000e+00, 4.41000000e+00, 2.97910000e+01, 2.82576100e+02,
       3.45025251e+03])

In [183]:
a

array([1, 2, 3, 4, 5])

In [184]:
a * 10

array([10, 20, 30, 40, 50])

In [185]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [186]:
a = np.arange(25).reshape(5, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [187]:
red = a[:,[1, 3]]
red

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [188]:
yellow = a[4,:]
yellow

array([20, 21, 22, 23, 24])

In [190]:
blue = a[1::2,:3:2]
blue

array([[ 5,  7],
       [15, 17]])

In [192]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [193]:
print(u + v)
print(u - v)
print(2 * v)

[ 5 11 13 12]
[-1  3 -3  0]
[ 6  8 16 12]


In [201]:
# Vector-vector multiplication
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]    
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

print(vector_vector_multiplication(u, v))
print(u.dot(v))

14.0
14


In [203]:
# Matrix-vector multiplication
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0] 
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

v = np.array([1, 0, 0, 2])

print(matrix_vector_multiplication(U, v))
print(U.dot(v))

[14.  5.  5.]
[14  5  5]


In [204]:
# Matrix-matrix multiplication
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    return result

U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
 
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 3, 1],
    [2, 1, 0]
])

print(matrix_matrix_multiplication(U, V))
print(U.dot(V))

[[14.  25.  13. ]
 [ 5.   7.   5. ]
 [ 5.  10.5  9. ]]
[[14.  25.  13. ]
 [ 5.   7.   5. ]
 [ 5.  10.5  9. ]]


In [197]:
# Identity matrix
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [199]:
# Inverse matrix
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])
inv = np.linalg.inv(V)
inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [205]:
I = np.eye(3)
print(I)

V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 3, 1],
    [2, 1, 0]
])
 
print(V.dot(I))
print(V.dot(I) == V)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1.  1.  2. ]
 [0.  0.5 1. ]
 [0.  3.  1. ]
 [2.  1.  0. ]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [208]:
# only squared matrices has an inverse matrix
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 3, 1]
])

# there is a function in numpy available that returns the inverse of a squared matrix
V_inv = np.linalg.inv(V)
print(V_inv)
 
# just to check that V_inv.dot(V) == I
print(V.dot(V_inv))

[[ 1.  -2.   0. ]
 [ 0.  -0.4  0.4]
 [ 0.   1.2 -0.2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
